config/routes.rb
Rails.application.routes.draw do
  resources :todos

  root 'welcome#index'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
    @todos = Todo.all
  end

  def new
  end

  def create
    @todo = Todo.new(todo_params)

    @todo.save
    redirect_to @todo
  end

  def show
    @todo = Todo.find(params[:id])
  end


  private
    def todo_params
      params.require(:todo).permit(:title, :text)
    end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/index.html.erb
<h1>Here's all the stuff you have to do</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @todos.each do |todo| %>
    <tr>
      <td><%= todo.title %> </td>
      <td><%= todo.text %> </td>
    </tr>
  <% end %>
</table>

app/views/todos/new.html.erb
<%= form_for :todo, url: todos_path do |f| %>
  <p>
    <%= f.label :title %> <br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :Thingy %> <br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/todos/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Text:</strong>
  <%=@todo.text %>
</p>

app/views/welcome/index.html.erb
<h1>This is your Todo app</h1>
<p>Find me in app/views/welcome/index.html.erb</p>